version: '3'

services:
  app-spring:
    build:
      context: .
      args:
        -JAR_FILE=*.jar
    container_name: app-spring
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tcc-postgres
      - SPRING_DATASOURCE_USERNAME=tcc-postgres
      - SPRING_DATASOURCE_PASSWORD=tcc-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=tcc-postgres
      - POSTGRES_PASSWORD=tcc-postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
      
      
  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
      - 25676:25676