version: '3'

services:
  app:
    image: 'openjdk:11'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tcc-postgres
      - SPRING_DATASOURCE_USERNAME=tcc-postgres
      - SPRING_DATASOURCE_PASSWORD=tcc-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=tcc-postgres
      - POSTGRES_PASSWORD=tcc-postgres
      
      
  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    port:
      - 15672:15672
      - 5672:5672
      - 25676:25676