app
  domain-name-url: ${DOMAIN_NAME_URL:localhost:8080}
spring:
  mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'false'
    show-sql: 'true'
  flyway:
    baseline-on-migrate: 'false'
    password: tcc-postgres
    user: tcc-postgres
    url: jdbc:postgresql://db:5432/tcc-postgres
  mail:
    username: ${YOUR_EMAIL}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
          ssl:
            trust: smtp.office365.com
            protocols: TLSv1.2
    default-encoding: UTF-8
    host: smtp.office365.com
    protocol: smtp
    test-connection: 'false'
    password: ${YOUR_PASSWORD}
  datasource:
    driverClassName: org.postgresql.Driver
    password: tcc-postgres
    username: tcc-postgres
    url: jdbc:postgresql://db:5432/tcc-postgres
  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
# remover sql.init.mode=always quando nao quiser que execute o data.sql
  sql:
    init:
      mode: never
hikari:
  max-lifetime: '50000'