spring:
  mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
  mail:
    username: youremail
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    default-encoding: UTF-8
    host: smtp.gmail.com
    protocol: smtp
    test-connection: 'false'
    password: yourpassword
  datasource:
    driverClassName: org.postgresql.Driver
    password: tcc-postgres
    username: tcc-postgres
    url: jdbc:postgresql://db:5432/tcc-postgres
  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
hikari:
  max-lifetime: '50000'
